use_frameworks!

platform :ios, '8.0'

target 'HSYQrCodeCameraToolsKit_Example' do
  pod 'HSYQrCodeCameraToolsKit', :path => '../'

  target 'HSYQrCodeCameraToolsKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
